---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
---

```{r setup, include=FALSE}
library(tidyverse)
library("p8105.datasets")
library(plotly)
library(flexdashboard)
```

```{r}
#load dataset
data("ny_noaa")

#tidy data
noaa_df = 
  ny_noaa %>% 
  #drop na values
  drop_na() %>% 
  #extrat year and month from the date column
  mutate(year = format(date, format = "%Y"),
         month = format(date, format = "%m"))
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
noaa_df %>% 
  #randomly select 3000 data points
  sample_n(3000) %>% 
  #calculate temperature range
  mutate(t_range = as.numeric(tmax) - as.numeric(tmin)) %>% 
  #plot boxplot showing temperature range for each year
  plot_ly(x = ~year, y = ~t_range, type = "box", colors = "viridis") %>% 
  #edit title, x/y axis title
  layout(title = "Temperature Range for each Year in NY",
         xaxis = list(title = "Year"),  
         yaxis = list(title = "Temperature Range (tenths of degree C)"))
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
noaa_df %>% 
  #filter the year
  filter(year == "1981") %>%
  #group data by month
  group_by(month) %>% 
  #find the mean of precipitation
  summarise(mean = mean(prcp)) %>% 
  #create bar plot
  plot_ly(x = ~month, y = ~mean, type = "bar", colors = "viridis") %>% 
  #edit title, x/y axis title
  layout(title = "Average Monthly Precipitation in 1981", 
         xaxis = list(title = "Month"),
         yaxis = list(title = "Average Precipitation (tenths of mm)"))
```

### Chart C

```{r}
noaa_df %>% 
  #group dataset by year
  group_by(year) %>% 
  #find the average snowfall for each year
  summarise(mean = mean(snow)) %>% 
  #create line plot
  plot_ly(x = ~year, y = ~mean,type = "scatter", mode = "line") %>% 
  #edit title, x/y axis title
  layout(title = "Average Yearly Snowfall in NY",
         xaxis = list(title = "Year"),
         yaxis = list(title = "Average Snowfall (mm)"))
```

